self.lexer.add('FLOAT', '-?\d+\.\d+')
self.lexer.add('INTEGER', '-?\d+')
self.lexer.add('STRING', '(""".*?""")|(".*?")|(\'.*?\')')
self.lexer.add('BOOLEAN', "true(?!\w)|false(?!\w)")

self.lexer.add('IF', 'if(?!\w)')
self.lexer.add('ELSE', 'else(?!\w)')
self.lexer.add('END', 'end(?!\w)')

self.lexer.add('AND', "and(?!\w)")
self.lexer.add('OR', "or(?!\w)")
self.lexer.add('NOT', "not(?!\w)")
self.lexer.add('FOR', 'for(?!\w)')
self.lexer.add('WHILE', 'while(?!\w)')
self.lexer.add('BREAK', 'break(?!\w)')
self.lexer.add('RETURN', 'return(?!\w)')

self.lexer.add('DEF', 'def(?!\w)')

self.lexer.add('IMPORT', 'import(?!\w)')
self.lexer.add('FROM', 'from(?!\w)')

self.lexer.add('IDENTIFIER', "[a-zA-Z_][a-zA-Z0-9_]*")
self.lexer.add('==', '==')
self.lexer.add('!=', '!=')
self.lexer.add('>=', '>=')
self.lexer.add('<=', '<=')
self.lexer.add('>', '>')
self.lexer.add('<', '<')
self.lexer.add('=', '=')
self.lexer.add('[', '\[')
self.lexer.add(']', '\]')
self.lexer.add('{', '\{')
self.lexer.add('}', '\}')
self.lexer.add('|', '\|')
self.lexer.add(',', ',')
self.lexer.add('PLUS', '\+')
self.lexer.add('DOT', '\.')
self.lexer.add(':', ':')
self.lexer.add('MINUS', '-')
self.lexer.add('MUL', '\*')
self.lexer.add('DIV', '/')
self.lexer.add('MOD', '%')
self.lexer.add('(', '\(')
self.lexer.add(')', '\)')
self.lexer.add('NEWLINE', '\n')
